cloud-native-toolkit/toolkit-charts

stable/developer-dashboard/Chart.yaml, stable/developer-dashboard/templates/_helpers.tpl, stable/developer-dashboard/templates/ingress.yaml, stable/developer-dashboard/templates/route.yaml, stable/developer-dashboard/values.yaml
- Updates apiVersion for ingress to remove deprecated reference
- Updates apiVersion for route so that chart can be installed with kubectl command
- Adds sso.enabled to values and updates route to point to the proxy port with reencrypt tls termination
ibm-garage-cloud/planning#123
=> Developer Dashboard v0.2.0

stable/service-account/Chart.yaml, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml, stable/service-account/templates/serviceaccount.yaml, stable/service-account/values.yaml
- Adds namespace prefix to scc names
- Adds labels to sccs to match service account
- Adds createNamespace flag to disable namespace creation (essentially create the sccs for an existing namespace)
=> service-account: v0.2.0

stable/service-account/Chart.yaml, stable/service-account/templates/_helpers.tpl, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml, stable/service-account/values.yaml
- Adds clusterType flag as condition for creating sccs
=> service-account: v0.2.1

stable/service-account/Chart.yaml, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml
- Save labels in scc resources into variables to fix error
=> service-account: v0.2.2

stable/ocp-route/Chart.yaml, stable/ocp-route/templates/route.yaml, stable/ocp-route/values.yaml
- Adds flag to conditionally create the route, defaulted to true
=> ocp-route: v0.2.0

stable/service-account/Chart.yaml, stable/service-account/templates/_helpers.tpl, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml, stable/service-account/values.yaml
- Adds support for global.clusterType
- Fixes logic for isOpenShift test
=> service-account: v0.2.3

stable/ocp-route/Chart.yaml, stable/ocp-route/templates/_helpers.tpl, stable/ocp-route/templates/route.yaml, stable/ocp-route/values.yaml
- Adds support for clusterType and global.clusterType
=> ocp-route: v0.3.0

stable/service-account/Chart.yaml, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml
- Fixes names of sccs and generates from sccs name
=> service-account: v0.3.0

stable/service-account/Chart.yaml, stable/service-account/templates/serviceaccount.yaml, stable/service-account/values.yaml
- Fixes name for createNamespace to just create
- Changes default clusterType to openshift to generate sccs if provided
=> service-account: v0.4.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/rbac.yaml
- Fixes problem with cluster role name
=> argocd-config: v0.12.3

stable/jaeger-operator/Chart.yaml, stable/jaeger-operator/templates/_helpers.tpl, stable/jaeger-operator/values.yaml
- Adds support for global.clusterType
=> jaeger-operator: v0.2.0

stable/jaeger-operator/Chart.yaml, stable/jaeger-operator/templates/instance.yaml, stable/jaeger-operator/values.yaml
- Exposes spec for instance in variables and provides a default value for allInOne in-memory
=> jaeger-operator: v0.3.0

stable/nexus-operator/.helmignore, stable/nexus-operator/Chart.yaml, stable/nexus-operator/templates/_helpers.tpl, stable/nexus-operator/templates/instance.yaml, stable/nexus-operator/templates/operatorgroup.yaml, stable/nexus-operator/templates/route.yaml, stable/nexus-operator/templates/subscription.yaml, stable/nexus-operator/values.yaml
- Adds helm chart to deploy nexus
=> nexus-operator: v0.1.0

stable/nexus-operator/Chart.yaml, stable/nexus-operator/templates/_helpers.tpl, stable/nexus-operator/templates/instance.yaml, stable/nexus-operator/values.yaml
- Adds required useRedHatImage flag with conditional logic for clusterType
=> nexus-operator: v0.2.0

stable/nexus-operator/Chart.yaml, stable/nexus-operator/templates/_helpers.tpl, stable/nexus-operator/templates/instance.yaml, stable/nexus-operator/templates/job-rbac.yaml, stable/nexus-operator/templates/job.yaml
- Adds job to get the secret from the pod and apply the tool-config chart
=> nexus-operator: v0.3.0

stable/developer-dashboard/Chart.yaml, stable/developer-dashboard/templates/_helpers.tpl, stable/developer-dashboard/templates/route.yaml, stable/developer-dashboard/values.yaml
- Allows iconUrl to be passed in to override default value
=> developer-dashboard: v1.2.0

stable/jaeger-operator/Chart.yaml, stable/jaeger-operator/templates/instance.yaml, stable/jaeger-operator/values.yaml
- Adds createInstance flag to allow just the subscription to be created
=> jaeger-operator: v0.5.0

stable/argocd-operator/Chart.yaml, stable/argocd-operator/templates/_helpers.tpl, stable/argocd-operator/templates/instance.yaml, stable/argocd-operator/templates/subscription.yaml, stable/argocd-operator/values.yaml
- Refresh to be consistent with other operator charts
- Adds namespaceScoped flag to install the operator into .Release.Namespace instead of operatorNamespace`
=> argocd-operator: v0.2.0

stable/elasticsearch-operator/Chart.yaml, stable/elasticsearch-operator/templates/subscription.yaml, stable/kiali-operator/Chart.yaml, stable/kiali-operator/templates/subscription.yaml, stable/service-mesh-operator/Chart.yaml, stable/service-mesh-operator/templates/subscription.yaml
- Fixes the subscription name
- Updates elasticsearch to wrap channel in quotes to fix number/string conversion issue
=> Updates to service-mesh, kiali, and elasticsearch

stable/service-mesh-operator/Chart.yaml, stable/service-mesh-operator/crds/banzaicloud-istio.crd.yaml, stable/service-mesh-operator/crds/banzaicloud-meshgateway.crd.yaml, stable/service-mesh-operator/crds/banzaicloud-remoteistio.crd.yaml, stable/service-mesh-operator/crds/maistra-controlplanes.crd.yaml, stable/service-mesh-operator/crds/maistra-memberrolls.crd.yaml, stable/service-mesh-operator/crds/maistra-members.crd.yaml
- Adds crds for maistra and banzaicloud versions of operator
=> service-mesh: v0.5.0

stable/tool-config/Chart.yaml, stable/tool-config/templates/_helpers.tpl, stable/tool-config/templates/application-menu.yaml
- Updates chart to generate application menu to not require ingressSubdomain if imageUrl is provided
=> tool-config: v0.7.1

stable/tekton-operator/Chart.yaml, stable/tekton-operator/crds/tekton.crds.yaml
- Includes tekton CRDs in helm chart
=> tekton-operator: v0.1.1

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/templates/applications.yaml, stable/argocd-config/templates/namespaces.yaml, stable/argocd-config/templates/project.yaml, stable/argocd-config/templates/rbac.yaml, stable/argocd-config/values.yaml
* Sets the default value for controllerRbac to false
* Adds labels to all the templates
=> argocd-config: v0.13.0

stable/tekton-operator/Chart.yaml, stable/tekton-operator/templates/subscription.yaml, stable/tekton-operator/values.yaml
- Removes jaeger reference from chart
- Sets subscription name to match operator name
=> tekton-operator: v0.2.0

stable/ibmcloud/Chart.yaml, stable/ibmcloud/templates/config-map.yaml, stable/ibmcloud/templates/secret.yaml
- Fixes indentation issue with labels in secret and configmap
=> ibmcloud: v0.2.1

stable/ibmcloud/Chart.yaml, stable/ibmcloud/templates/_helpers.tpl
=> ibmcloud: v0.2.2

stable/setup-job/.helmignore, stable/setup-job/Chart.yaml, stable/setup-job/templates/_helpers.tpl, stable/setup-job/templates/job.yaml, stable/setup-job/values.yaml
- Adds chart to set up a job to update a tool after it is installed
=> setup-job: v0.1.0

stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml
=> setup-job: v0.1.1

stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml
- Fixes include references in job
=> setup-job: v0.1.2

stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml
- Updates image used to wait for Artifactory
=> setup-job: v0.1.3

stable/setup-job/Chart.yaml, stable/setup-job/templates/_helpers.tpl, stable/setup-job/templates/job.yaml
- Updates fullname helper template to use setup-job.name as the base
- Updates job definition to fix permissions issues in container
=> setup-job: v0.1.4

stable/service-account/Chart.yaml, stable/service-account/templates/rbac.yaml, stable/service-account/values.yaml
- Adds support for generating role and role binding along with service account if roles value provided
=> service-account: v0.5.0

stable/setup-job/Chart.yaml, stable/setup-job/templates/_helpers.tpl, stable/setup-job/templates/job.yaml
=> setup-job: v0.1.5

stable/doc-config/.helmignore, stable/doc-config/Chart.yaml, stable/doc-config/templates/_helpers.tpl, stable/doc-config/templates/help-menu.yaml, stable/doc-config/values.yaml
- Adds chart to generate helm-menu in OpenShift cluster
ibm-garage-cloud/planning#500
=> doc-config: v0.1.0

stable/ibmcloud/Chart.yaml, stable/ibmcloud/templates/config-map.yaml, stable/ibmcloud/templates/secret.yaml, stable/ibmcloud/values.yaml
- Updates config values to make IBM Cloud-specific values optional
=> ibmcloud: v0.3.0

stable/ibmcloud/Chart.yaml, stable/ibmcloud/templates/config-map.yaml, stable/ibmcloud/templates/secret.yaml, stable/ibmcloud/values.yaml
- Fixes conditional statements in config-map to create value properly
=> ibmcloud: v0.3.1

stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml
=> setup-job: v0.1.6

stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml, stable/setup-job/values.yaml
- Exposes cliVersion through helm values
=> setup-job: v0.1.7

stable/ibmcloud-operator/.helmignore, stable/ibmcloud-operator/Chart.yaml, stable/ibmcloud-operator/templates/_helpers.tpl, stable/ibmcloud-operator/templates/configmap.yaml, stable/ibmcloud-operator/templates/operatorgroup.yaml, stable/ibmcloud-operator/templates/secret.yaml, stable/ibmcloud-operator/templates/subscription.yaml, stable/ibmcloud-operator/values.yaml, stable/values.yaml
- Initial version of chart to install ibmcloud-operator subscription and create required supporting configuration
=> ibmcloud-operator: v0.1.0

stable/ibmcloud-operator/Chart.yaml, stable/ibmcloud-operator/templates/configmap.yaml, stable/ibmcloud-operator/templates/operatorgroup.yaml, stable/ibmcloud-operator/templates/secret.yaml
- Cleans up handling of labels and adds labels to operatorgroup
=> ibmcloud-operator: v0.1.1

stable/tool-test/Chart.yaml, stable/tool-test/templates/deployment.yaml, stable/tool-test/templates/service.yaml
- Adds deployment to make route valid
=> tool-test: v0.2.0

stable/tool-test/Chart.yaml, stable/tool-test/templates/route.yaml
=> tool-test: v0.2.1

stable/iteration-zero/.helmignore, stable/iteration-zero/Chart.yaml, stable/iteration-zero/templates/_helpers.tpl, stable/iteration-zero/templates/deployment.yaml, stable/iteration-zero/templates/rbac.yaml, stable/iteration-zero/templates/serviceaccount.yaml, stable/iteration-zero/values.yaml
- Adds chart to create pod with izero cli-tools and necessary rbac to install the toolkit in-cluster
=> iteration-zero: v0.1.0

stable/developer-dashboard/Chart.yaml, stable/developer-dashboard/templates/deployment.yaml, stable/developer-dashboard/values.yaml
- Adds annotation for dashboard vcs url and ref
ibm-garage-cloud/planning#233
=> developer-dashboard: v1.2.1

stable/tool-config/Chart.yaml, stable/tool-config/templates/_helpers.tpl, stable/tool-config/values.yaml
- Adds support to get image value using type value
=> tool-config: v0.10.0

stable/tool-config/Chart.yaml, stable/tool-config/templates/_helpers.tpl, stable/tool-config/templates/application-menu.yaml
- Fixes formatting issue for image url in application-menu
- Simplifies helper logic for handling type attribute
=> tool-config: v0.10.1

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/deployment.yaml, stable/starter-kit/templates/route.yaml, stable/starter-kit/templates/service.yaml, stable/starter-kit/values.yaml
- Adds optional sidecar container for graphql endpoint
=> starter-kit: v0.2.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml
=> force the creation of namespace in argocd-config chart

stable/nexus-operator/Chart.yaml, stable/nexus-operator/templates/job.yaml, stable/setup-job/Chart.yaml, stable/setup-job/templates/job.yaml
Related to https://github.com/ibm-garage-cloud/planning/issues/703
=> update images to point to quay

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/_helpers.tpl, stable/starter-kit/values.yaml
Adds resource limits to helm chart
=> starter-kit: v0.3.0

stable/starter-kit/Chart.yaml
=> starter-kit: v0.4.0

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/_helpers.tpl
=> starter-kit: v0.4.1

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/deployment.yaml
- Removes annotations section from deployment if it would be empty
=> starter-kit: v0.4.2

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/deployment.yaml
- Fixes annotation logic for deployment
=> starter-kit: v0.4.3

stable/cp-platform-navigator/.helmignore, stable/cp-platform-navigator/Chart.yaml, stable/cp-platform-navigator/templates/_helpers.tpl, stable/cp-platform-navigator/templates/instance.yaml, stable/cp-platform-navigator/templates/subscription.yaml, stable/cp-platform-navigator/values.yaml
- Adds chart to create operator subscription and instance for the CP platform navigator
=> cp-platform-navigator: v0.1.0

stable/starter-kit/Chart.yaml, stable/starter-kit/templates/deployment.yaml
- Change liveness and readiness probes to tcpSocket
=> starter-kit: v0.6.0

stable/ocs-operator/.helmignore, stable/ocs-operator/Chart.yaml, stable/ocs-operator/templates/_helpers.tpl, stable/ocs-operator/templates/storage-namespace.yaml, stable/ocs-operator/templates/storage-operatorgroup.yaml, stable/ocs-operator/templates/storage-rook-configmap.yaml, stable/ocs-operator/templates/storage-storagecluster.yaml, stable/ocs-operator/templates/storage-subscription.yaml, stable/ocs-operator/values.yaml, stable/refarch-infraconfig/.helmignore, stable/refarch-infraconfig/Chart.yaml, stable/refarch-infraconfig/templates/_helpers.tpl, stable/refarch-infraconfig/templates/infrastructure-imageregistry.yaml, stable/refarch-infraconfig/templates/infrastructure-ingresscontroller.yaml, stable/refarch-infraconfig/templates/infrastructure-monitoring-configmap.yaml, stable/refarch-infraconfig/values.yaml, stable/refarch-machinesets/.helmignore, stable/refarch-machinesets/Chart.yaml, stable/refarch-machinesets/templates/cloudpak-machineset.yaml, stable/refarch-machinesets/templates/infrastructure-machineset.yaml, stable/refarch-machinesets/templates/storage-machineset.yaml, stable/refarch-machinesets/values.yaml
1. create machinesets for storage, infra and cp4x nodes
2. deploy openshift container storage to storage machines
3. move infra components to infra nodes
=> machinesets + infra + storage

stable/elasticsearch-operator/Chart.yaml, stable/elasticsearch-operator/templates/operatorgroup.yaml, stable/jaeger-operator/Chart.yaml, stable/jaeger-operator/templates/namespaces.yaml
Signed-off-by: Carlos Santana <csantana23@gmail.com>
=> fix bug on elastic and jaeger

stable/refarch-machinesets/templates/cloudpak-machineset-vsphere.yaml, stable/refarch-machinesets/templates/infrastructure-machineset-vsphere.yaml, stable/refarch-machinesets/templates/storage-machineset-vsphere.yaml, stable/refarch-machinesets/values-vmware.yaml
=> change machinesets to per provider templates

stable/ocp-console-notification/Chart.yaml, stable/ocp-console-notification/templates/console-notification.yaml, stable/ocp-console-notification/values.yaml
- Only create resource if text is provided
=> ocp-console-notification: v0.2.0

stable/ocp-console-cli-download/Chart.yaml, stable/ocp-console-cli-download/templates/console-cli-download.yaml, stable/ocp-console-cli-download/values.yaml
- Handles long strings for description
=> ocp-console-cli-download: v0.2.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/templates/applications.yaml, stable/argocd-config/templates/project.yaml, stable/argocd-config/values.yaml
- Looks for repoUrl in global values
=> argocd-config: v0.17.1

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml, stable/argocd-config/values.yaml
- Allows syncWave to be provided for each application
=> argocd-config: v0.17.2

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/project.yaml, stable/argocd-config/values.yaml
- Adds destinations values at local scope to match global destinations
=> argocd-config: v0.17.3

stable/openshift-gitops/Chart.yaml, stable/openshift-gitops/templates/instance-config-map.yaml, stable/openshift-gitops/templates/instance-job.yaml
- Updates job to use quay.io/bitnami/kubectl:latest
- Runs kubectl for job commands
=> openshift-gitops: v0.2.0

stable/openshift-gitops/Chart.yaml
=> openshift-gitops: v0.2.1

stable/openshift-gitops/Chart.yaml
=> openshift-gitops: v0.3.0

stable/argocd-operator/Chart.yaml
=> argocd-operator: v0.3.1

stable/argocd-operator/Chart.yaml, stable/argocd-operator/templates/_helpers.tpl
=> argocd-operator: v0.3.2

stable/argocd-operator/Chart.yaml, stable/argocd-operator/templates/_helpers.tpl, stable/argocd-operator/templates/instance-config-map.yaml
- Fixes missing variables in config map
=> argocd-operator: v0.4.0

README.md
=> update urls for chart domain

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/templates/applications.yaml, stable/argocd-config/templates/project.yaml, stable/argocd-config/values.yaml
- Adds global variables for targetNamespace and targetRevision
=> argocd-config: v0.18.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/templates/applications.yaml
- Fixes invalid $.Values references
=> argocd-config: v0.18.1

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl
- Tests for targetNamespace value before creating destination
=> argocd-config: v0.18.2

stable/openshift-gitops/Chart.yaml, stable/openshift-gitops/templates/instance-config-map.yaml, stable/openshift-gitops/values.yaml
- Exposes variables for dex.openShiftOAuth and dex.image in values.yaml
=> openshift-gitops: v0.5.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl
- Wraps target namespace and server in quotes to handle "*"
=> argocd-config: v0.18.3

stable/developer-dashboard/Chart.yaml, stable/developer-dashboard/templates/route.yaml
- Fixes new lines around if block in route annotations
- Adds quote function for enable label and annotation
=> developer-dashboard: v1.3.1

stable/console-link-cronjob/Chart.yaml, stable/console-link-cronjob/templates/configmap.yaml
- Updates reconcile-console-links.sh to handle errors
=> console-link-cronjob: v0.1.2

stable/ibm-toolkit-install/.helmignore, stable/ibm-toolkit-install/Chart.yaml, stable/ibm-toolkit-install/templates/_helpers.tpl, stable/ibm-toolkit-install/templates/cluster-role-binding.yaml, stable/ibm-toolkit-install/templates/config-map.yaml, stable/ibm-toolkit-install/templates/job.yaml, stable/ibm-toolkit-install/templates/serviceaccount.yaml, stable/ibm-toolkit-install/values.yaml
- Adds chart to run terraform as a job in the cluster
- Parameterized git repo containing terraform and config values for execution
=> ibm-toolkit-install: v0.1.0

stable/ibm-toolkit-install/Chart.yaml, stable/ibm-toolkit-install/templates/cluster-role-binding.yaml, stable/ibm-toolkit-install/templates/config-map.yaml, stable/ibm-toolkit-install/templates/job.yaml, stable/ibm-toolkit-install/templates/serviceaccount.yaml
- Adds namespace value to configmap, job, and serviceaccount
- Adds labels to all resources
=> ibm-toolkit-install: v0.2.0

stable/ibm-toolkit-install/Chart.yaml, stable/ibm-toolkit-install/templates/config-map.yaml
- Fixes if statement in configmap template
- Removes whitespace in configmap data block
=> ibm-toolkit-install: v0.2.1

stable/slack-notifications/.helmignore, stable/slack-notifications/Chart.yaml, stable/slack-notifications/templates/_helpers.tpl, stable/slack-notifications/templates/broker.yaml, stable/slack-notifications/templates/deployment.yaml, stable/slack-notifications/templates/secret.yaml, stable/slack-notifications/templates/service.yaml, stable/slack-notifications/templates/trigger.yaml, stable/slack-notifications/values.yaml
Add helm chart to deploy Slack notifications.
- Use sealed secret for slack url
related to cloud-native-toolkit/planning#745
=> 92 notifications kustomize

stable/ocp-route/Chart.yaml, stable/ocp-route/templates/route.yaml, stable/ocp-route/values.yaml
- Adds annotations to route for console link generation
=> ocp-route: v0.4.0

stable/console-link-cronjob/Chart.yaml, stable/console-link-cronjob/templates/configmap.yaml, stable/console-link-cronjob/templates/rbac.yaml
- Generates config map in same namespace as route based on annotations
- Adds permission to create config maps in rbac
=> console-link-cronjob: v0.2.0

stable/console-link-cronjob/Chart.yaml, stable/console-link-cronjob/templates/configmap.yaml
- Updates label for cloud-native-toolkit group
=> console-link-cronjob: v0.2.1

stable/openshift-serverless/.helmignore, stable/openshift-serverless/Chart.yaml, stable/openshift-serverless/templates/_helpers.tpl, stable/openshift-serverless/templates/subscription.yaml, stable/openshift-serverless/values.yaml, stable/slack-notifications/values.yaml
Add Openshift Serverless chart
=> 92 openshift serverless

stable/slack-notifications/Chart.yaml, stable/slack-notifications/values.yaml
change slack secret name and key values
=> Change slack secret name and key

stable/openshift-serverless/Chart.yaml
Update chart version so it will push to index.yaml
Signed-off-by: Larry Steck <lsteck@us.ibm.com>
=> update openshift-serverless chart version

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml
- Fixes missing printf for the pathSuffix
=> argocd-config: v0.19.1

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml
- Removes 'helm' default for application type
=> argocd-config: v0.19.2

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml
=> argocd-config: v0.19.3

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml
- Only include the revision/branch in the application name if the branch is not main or master
=> argocd-config: v0.20.0

stable/ibm-process-mining-instance/.helmignore, stable/ibm-process-mining-instance/Chart.yaml, stable/ibm-process-mining-instance/templates/_helpers.tpl, stable/ibm-process-mining-instance/templates/instance.yaml, stable/ibm-process-mining-instance/values.yaml
Signed-off-by: Carlos Santana <csantana23@gmail.com>
=> add process mining instance helm chart

stable/ibm-process-mining-instance/Chart.yaml, stable/ibm-process-mining-instance/values.yaml
Signed-off-by: Carlos Santana <csantana23@gmail.com>
=> bug name missing in default values.yaml

stable/console-link-cronjob/Chart.yaml, stable/console-link-cronjob/templates/cronjob.yaml
- Fixes cronjob command and args config
=> console-link-cronjob: v0.4.2

stable/console-link-cronjob/Chart.yaml, stable/console-link-cronjob/scripts/reconcile-ibm-observe-console-links.sh, stable/console-link-cronjob/templates/configmap.yaml
- Fixes bug in reconcile-ibm-observe-console-links.sh script of not testing for agent name correctly
=> console-link-cronjob: v0.5.1

stable/ocs-operator/Chart.yaml
=> bump storage chart to 0.2.4

stable/namespace-rbac-cronjob/.helmignore, stable/namespace-rbac-cronjob/Chart.yaml, stable/namespace-rbac-cronjob/README.md, stable/namespace-rbac-cronjob/config/default-role.yaml, stable/namespace-rbac-cronjob/scripts/_update-configmap.sh, stable/namespace-rbac-cronjob/scripts/reconcile-namespace-rbac.sh, stable/namespace-rbac-cronjob/support/configmap.snippet.yaml, stable/namespace-rbac-cronjob/templates/_helpers.tpl, stable/namespace-rbac-cronjob/templates/configmap-rbac.yaml, stable/namespace-rbac-cronjob/templates/configmap.yaml, stable/namespace-rbac-cronjob/templates/cronjob.yaml, stable/namespace-rbac-cronjob/templates/rbac.yaml, stable/namespace-rbac-cronjob/templates/serviceaccount.yaml, stable/namespace-rbac-cronjob/values.yaml
- Initial version of cronjob to create RBAC for a particular service account when a label is applied to the namespace
=> namespace-rbac-cronjob: v0.1.0

stable/ibm-automation-foundation-core-operator/Chart.yaml, stable/ibm-automation-foundation-core-operator/values.yaml, stable/ocp-subscription/.helmignore, stable/ocp-subscription/Chart.yaml, stable/ocp-subscription/templates/_helpers.tpl, stable/ocp-subscription/templates/subscription.yaml, stable/ocp-subscription/values.yaml
Add generic ocp-subscription chart to be use by argocd
=> Add generic ocp-subscription chart to be use by argocd

stable/namespace-rbac-cronjob/Chart.yaml, stable/namespace-rbac-cronjob/values.yaml
- Adds sealed secrets to default rbac
- Updates schedule to run every minute
=> namespace-rbac-cronjob: v0.2.0

stable/assign-group-cronjob/.helmignore, stable/assign-group-cronjob/Chart.yaml, stable/assign-group-cronjob/README.md, stable/assign-group-cronjob/scripts/_update-configmap.sh, stable/assign-group-cronjob/scripts/reconcile-users-in-group.sh, stable/assign-group-cronjob/support/configmap.snippet.yaml, stable/assign-group-cronjob/templates/_helpers.tpl, stable/assign-group-cronjob/templates/configmap.yaml, stable/assign-group-cronjob/templates/cronjob.yaml, stable/assign-group-cronjob/templates/rbac.yaml, stable/assign-group-cronjob/templates/serviceaccount.yaml, stable/assign-group-cronjob/values.yaml
- Initial version of cronjob to add users to provided group
=> assign-group-cronjob: v0.1.0

stable/ocp-route/Chart.yaml, stable/ocp-route/templates/route.yaml, stable/ocp-route/values.yaml
- Adds category annotation to route
=> ocp-route: v0.5.0

stable/developer-dashboard/Chart.yaml, stable/developer-dashboard/templates/route.yaml
- Adds category annotation to route
=> developer-dashboard: v1.4.1

stable/gitea-instance/.helmignore, stable/gitea-instance/Chart.yaml, stable/gitea-instance/templates/_helpers.tpl, stable/gitea-instance/templates/gitea.yaml, stable/gitea-instance/templates/secret.yaml, stable/gitea-instance/values.yaml, stable/gitea-operator/.helmignore, stable/gitea-operator/Chart.yaml, stable/gitea-operator/templates/_helpers.tpl, stable/gitea-operator/templates/catalogsource.yaml, stable/gitea-operator/templates/subscription.yaml, stable/gitea-operator/values.yaml
Install Gitea via Red Hat Operator
fix cloud-native-toolkit/planning#860
=> 860 gitea install

stable/ibm-cp4d-watson-studio-instance/.helmignore, stable/ibm-cp4d-watson-studio-instance/Chart.yaml, stable/ibm-cp4d-watson-studio-instance/templates/_helpers.tpl, stable/ibm-cp4d-watson-studio-instance/templates/instance.yaml, stable/ibm-cp4d-watson-studio-instance/values.yaml, stable/ibm-cp4sthreatmanagements-instance/.helmignore, stable/ibm-cp4sthreatmanagements-instance/Chart.yaml, stable/ibm-cp4sthreatmanagements-instance/templates/_helpers.tpl, stable/ibm-cp4sthreatmanagements-instance/templates/instance.yaml, stable/ibm-cp4sthreatmanagements-instance/values.yaml
=> Add watson studio and cp4s instance charts

stable/ibm-cpd-platform-instance/.helmignore, stable/ibm-cpd-platform-instance/Chart.yaml, stable/ibm-cpd-platform-instance/templates/_helpers.tpl, stable/ibm-cpd-platform-instance/templates/instance.yaml, stable/ibm-cpd-platform-instance/templates/operandrequest.yaml, stable/ibm-cpd-platform-instance/values.yaml
Issue: https://github.com/cloud-native-toolkit/toolkit-charts/issues/271
=> Add chart for CP4D Platform instance

stable/ibm-automation-foundation-core-operator/values.yaml, stable/ibm-catalogs/Chart.yaml, stable/ibm-catalogs/templates/ibm-db2u-operator-catalog.yaml, stable/ibm-catalogs/values.yaml, stable/ibm-db2u-operator/.helmignore, stable/ibm-db2u-operator/Chart.yaml, stable/ibm-db2u-operator/templates/_helpers.tpl, stable/ibm-db2u-operator/templates/subscription.yaml, stable/ibm-db2u-operator/values.yaml, stable/ibm-process-mining-instance/Chart.yaml, stable/ibm-process-mining-instance/values.yaml, stable/ibm-process-mining-operator/Chart.yaml, stable/ibm-process-mining-operator/values.yaml
Signed-off-by: Jesus Almaraz <jesus.mah@gmail.com>
=> pm refactor new operator version

stable/instana-robot-shop/Chart.yaml, stable/instana-robot-shop/templates/web-deployment.yaml, stable/instana-robot-shop/values.yaml
Issue: https://github.com/cloud-native-toolkit/toolkit-charts/issues/274
=> Update robot-shop chart to accept secret containing instana key

stable/ibm-toolkit-install/Chart.yaml, stable/ibm-toolkit-install/values.yaml
=> ibm-toolkit-install: v0.3.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/templates/applications.yaml, stable/argocd-config/templates/project.yaml, stable/argocd-config/values.yaml
- Adds support for prefix value in globals and values to reduce collisions
=> argocd-config: v0.21.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/project.yaml
- Adds sync-options annotation to project to set Prune=false
=> argocd-config: v0.22.0

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/_helpers.tpl, stable/argocd-config/values.yaml
- Adds part-of label to resources if groupLabel or global.groupLabel is set
=> argocd-config: v0.23.0

stable/ibm-cp4d-watson-studio-instance/Chart.yaml, stable/ibm-cp4d-watson-studio-instance/templates/instance.yaml, stable/ibm-cp4d-watson-studio-instance/values.yaml, stable/ibm-cpd-platform-instance/Chart.yaml, stable/ibm-cpd-platform-instance/templates/instance.yaml, stable/ibm-cpd-platform-instance/values.yaml
=> Update CP4D charts for 4.0.4 release

stable/ibm-catalogs/Chart.yaml, stable/ibm-catalogs/templates/ibm-db2u-operator-catalog.yaml
- Adds sync-wave annotation to db2u catalog
=> ibm-catalogs: v0.3.1

stable/odf-operator/.helmignore, stable/odf-operator/Chart.yaml, stable/odf-operator/templates/_helpers.tpl, stable/odf-operator/templates/storage-operatorgroup.yaml, stable/odf-operator/templates/storage-post-sync-job.yaml, stable/odf-operator/templates/storage-rook-configmap.yaml, stable/odf-operator/templates/storage-storagecluster.yaml, stable/odf-operator/templates/storage-storagesystem.yaml, stable/odf-operator/templates/storage-subscription.yaml, stable/odf-operator/values.yaml, stable/refarch-machinesets/templates/_cloud_defaults.tpl, stable/refarch-machinesets/templates/_machineset_defaults.tpl, stable/refarch-machinesets/templates/_machinesets.tpl, stable/refarch-machinesets/values.yaml
=> odf-operator and ibmcloud machineset updates

stable/ibm-eventstreams-instance/.helmignore, stable/ibm-eventstreams-instance/Chart.yaml, stable/ibm-eventstreams-instance/templates/_helpers.tpl, stable/ibm-eventstreams-instance/templates/instance.yaml, stable/ibm-eventstreams-instance/values.yaml, stable/ibm-eventstreams-operator/values.yaml
Signed-off-by: Jesus Almaraz <jesus.mah@gmail.com>
=> Adding Event Streams Operator and Instance

stable/ibm-cpd-ds-instance/.helmignore, stable/ibm-cpd-ds-instance/Chart.yaml, stable/ibm-cpd-ds-instance/templates/_helpers.tpl, stable/ibm-cpd-ds-instance/templates/instance.yaml, stable/ibm-cpd-ds-instance/values.yaml
=> Add chart for DataStage

stable/rhacm-hivecluster/Chart.yaml, stable/rhacm-hivecluster/templates/clusterdeployment.yaml
=> remove installed:false from hivecluster

stable/rhacm-hivecluster/Chart.yaml, stable/rhacm-hivecluster/templates/bootstrap.yaml
=> update hivecluster 0.2.3

stable/rhacm-hivecluster/Chart.yaml, stable/rhacm-hivecluster/templates/bootstrap.yaml
=> bump hivecluster 0.2.4

stable/service-signed-cert/.helmignore, stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/README.md, stable/service-signed-cert/templates/_helpers.tpl, stable/service-signed-cert/templates/config-map.yaml, stable/service-signed-cert/templates/job.yaml, stable/service-signed-cert/templates/rbac.yaml, stable/service-signed-cert/templates/serviceaccount.yaml, stable/service-signed-cert/values.yaml
- Adds implementation of job to create and approve CSR
Closes #309
=> service-signed-cert: v0.1.0

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/templates/config-map.yaml, stable/service-signed-cert/templates/job.yaml, stable/service-signed-cert/templates/rbac.yaml, stable/service-signed-cert/templates/serviceaccount.yaml
=> service-signed-cert: v0.2.0

stable/openshift-gitops/Chart.yaml, stable/openshift-gitops/templates/rbac.yaml
Fixes typo in rbac group name
Closes #313
=> openshift-gitops: v0.8.1

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/approve-csr.sh, stable/service-signed-cert/scripts/create-csr.sh, stable/service-signed-cert/templates/configmap.yaml, stable/service-signed-cert/templates/rbac.yaml
Updates cluster role permissions to allow approving csrs from kubernetes.io/legacy-unknown signer
Closes #319
=> service-signed-cert: v0.2.3

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/templates/job.yaml
Removes checksum annotation from job pod template
Closes #325
=> service-signed-cert: v0.3.1

stable/openshift-gitops-instance/Chart.yaml, stable/openshift-gitops-instance/templates/instance.yaml
- Sets namespace on argocd instance
=> openshift-gitops-instance: v0.3.1

stable/ibm-portworx/.helmignore, stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/README.md, stable/ibm-portworx/scripts/_update-configmap.sh, stable/ibm-portworx/scripts/volume-attach.sh, stable/ibm-portworx/scripts/volume-attachment-destroy.sh, stable/ibm-portworx/scripts/volume-create.sh, stable/ibm-portworx/scripts/volume-manage.sh, stable/ibm-portworx/scripts/wipe_portworx.sh, stable/ibm-portworx/scripts/write-config-secret.sh, stable/ibm-portworx/support/configmap.snippet.yaml, stable/ibm-portworx/templates/_helpers.tpl, stable/ibm-portworx/templates/configmap.yaml, stable/ibm-portworx/templates/daemonset.yaml, stable/ibm-portworx/templates/job.yaml, stable/ibm-portworx/templates/portworx-service.yaml, stable/ibm-portworx/templates/rbac.yaml, stable/ibm-portworx/templates/secret.yaml, stable/ibm-portworx/templates/serviceaccount.yaml, stable/ibm-portworx/values.yaml
- Deploys a daemonset to provision and attach a volume to each node
- Provisions the portworx service using the IBM Cloud Operator
=> ibm-portworx: v0.1.0

stable/service-signed-cert/scripts/create-secret.sh
=> removed base64 -D when creating cert

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/serviceaccount.yaml
- Fixes handling of annotations in service account
=> ibm-portworx: v0.2.2

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh
=> added tls key/crt keys to configmap

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/templates/configmap.yaml
=> updated mongo chart

stable/service-signed-cert/scripts/create-secret.sh, stable/service-signed-cert/templates/configmap.yaml
=> debugging create secret script

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh
=> service-signed-cert: v0.3.8

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/templates/configmap.yaml
=> service-signed-cert: v0.3.10

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh
=> service-signed-cert: updated signing keys

stable/ibmcloud-operator/Chart.yaml, stable/ibmcloud-operator/templates/subscription.yaml
- Adds resource configuration to subscription to prevent out of memory errors in the operator
=> ibmcloud-operator: v0.2.1

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh, stable/service-signed-cert/templates/configmap.yaml
=> service-signed-cert-0.3.12

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh, stable/service-signed-cert/templates/configmap.yaml
=> service-signed-cert-0.3.13

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-secret.sh, stable/service-signed-cert/templates/configmap.yaml
=> service-signed-cert-0.3.14

stable/argocd-operator/Chart.yaml, stable/argocd-operator/templates/instance-job.yaml, stable/openshift-gitops-instance/Chart.yaml, stable/openshift-gitops-instance/templates/instance-job.yaml
fixes https://github.com/cloud-native-toolkit/toolkit-charts/issues/362
=> updated bitnami/kubectl from quay to docker

stable/cloud-portworx/.helmignore, stable/cloud-portworx/Chart.yaml, stable/cloud-portworx/templates/_helpers.tpl, stable/cloud-portworx/templates/operator-group.yaml, stable/cloud-portworx/templates/secret.yaml, stable/cloud-portworx/templates/storage-classes.yaml, stable/cloud-portworx/templates/storage-cluster.yaml, stable/cloud-portworx/templates/subscription.yaml, stable/cloud-portworx/values.yaml
Installs portworx via the portworx operator and configures the instance via a storagecluster instance
=> cloud-portworx: v0.1.0

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/rbac.yaml
Fixes alignment typo in rbac.yaml
=> ibm-portworx: v0.4.1

stable/tool-config/Chart.yaml, stable/tool-config/templates/_helpers.tpl, stable/tool-config/templates/application-menu.yaml, stable/tool-config/templates/config-map.yaml, stable/tool-config/templates/secret.yaml, stable/tool-config/values.yaml
- Upgrades to a v2 chart
- Adds namespace to secret and configmap
- Exposes location in values.yaml
=> tool-config: v0.13.0

stable/tekton-operator/Chart.yaml, stable/tekton-operator/templates/_helpers.tpl, stable/tekton-operator/templates/operatorgroup.yaml, stable/tekton-operator/values.yaml
Adds createdBy value to set created-by label
=> tekton-operator: v0.2.1

stable/tekton-operator/Chart.yaml, stable/tekton-operator/templates/subscription.yaml
Removes pre-install hook annotation on subscription
=> tekton-operator: v0.3.1

stable/argocd-config/Chart.yaml, stable/argocd-config/templates/applications.yaml, stable/argocd-config/values.yaml
- Adds "cascadingDelete" flag, defaulted to `true`
- Adds `resources-finalizer.argocd.argoproj.io` finalizer to argo applications if "cascadingDelete" value is true
cloud-native-toolkit/software-everywhere#197
=> argocd-config: v0.24.0

stable/tekton-operator/Chart.yaml, stable/tekton-operator/templates/post-install-hook.yaml
- Adds post-upgrade hook to job
=> tekton-operator: v0.3.2

stable/ibm-cp4sthreatmanagements-instance/Chart.yaml, stable/ibm-cp4sthreatmanagements-instance/templates/instance.yaml
=> Update cp4s chart

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/scripts/support-functions.sh, stable/ibm-portworx/scripts/volume-create.sh, stable/ibm-portworx/support/configmap-delete.snippet.yaml, stable/ibm-portworx/support/configmap.snippet.yaml
- Fixes bug in create script
- Adds more logging for install scripts
=> ibm-portworx: v0.4.2

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/configmap.yaml
- Regenerates configmap with script changes...
=> ibm-portworx: v0.4.3

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/scripts/volume-create.sh
- Updates logic to only apply IOPS config if profile is "custom"
=> ibm-portworx: v0.6.2

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/configmap.yaml, stable/ibm-portworx/values.yaml
- Regenerates configmap
- Sets default iops value to empty string
=> ibm-portworx: v0.6.3

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/scripts/_update-configmap.sh, stable/ibm-portworx/scripts/update-resource-owner.sh, stable/ibm-portworx/scripts/wipe_portworx.sh, stable/ibm-portworx/templates/_helpers.tpl, stable/ibm-portworx/templates/configmap.yaml, stable/ibm-portworx/templates/owner-job.yaml, stable/ibm-portworx/templates/post-delete-hook-config.yaml, stable/ibm-portworx/values.yaml
- Adds job to set ownerReferences on resources left behind by portworx helm chart
=> ibm-portworx: v0.7.0

stable/service-signed-cert/Chart.yaml, stable/service-signed-cert/scripts/create-csr.sh, stable/service-signed-cert/templates/configmap.yaml
- Updates CertificateSigningCert to certificates.k8s.io/v1
closes #395
=> service-signed-cert: v0.3.15

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/configmap.yaml
- Regenerates config map to pick up script change
=> ibm-portworx: v0.8.2

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/scripts/update-resource-owner.sh, stable/ibm-portworx/values.yaml
- Adds name to ownerReferences value
- Updates cli-tools image to v1.1-v1.8.2
=> ibm-portworx: v0.8.3

stable/ibm-portworx/Chart.yaml, stable/ibm-portworx/templates/configmap.yaml
- Updates configmap with shell script changes
=> ibm-portworx: v0.8.4

stable/ibm-cp4d-data-virtualization-instance/.helmignore, stable/ibm-cp4d-data-virtualization-instance/Chart.yaml, stable/ibm-cp4d-data-virtualization-instance/templates/_helpers.tpl, stable/ibm-cp4d-data-virtualization-instance/templates/instance.yaml, stable/ibm-cp4d-data-virtualization-instance/values.yaml
Signed-off-by: Bijo Thomas <64802013+atbijo@users.noreply.github.com>
=> CP4D Data Virtualization Charts

stable/pact-broker/Chart.yaml
Signed-off-by: Ramya Raghuveera <ramragh1@in.ibm.com>
=> Upgrading pact broker image version

stable/ibm-eventstreams-instance/Chart.yaml, stable/ibm-eventstreams-instance/templates/instance.yaml, stable/ibm-eventstreams-instance/values.yaml
Signed-off-by: Jesus Almaraz <jesus.mah@gmail.com>
=> New Event Streams Helm chart for ES v11

stable/iteration-zero/Chart.yaml, stable/iteration-zero/values.yaml
- Updates container image to v1.1-v1.8.2
=> iteration-zero: v0.2.0

stable/ocp-service-tls/Chart.yaml, stable/ocp-service-tls/support/configmap.snippet.yaml, stable/ocp-service-tls/templates/_helpers.tpl, stable/ocp-service-tls/templates/configmap.yaml, stable/ocp-service-tls/templates/job.yaml, stable/ocp-service-tls/templates/rbac.yaml, stable/ocp-service-tls/templates/serviceaccount.yaml, stable/ocp-service-tls/values.yaml
- Adds global.syncWave support
=> ocp-service-tls: v0.2.0

stable/ocp-service-tls/Chart.yaml, stable/ocp-service-tls/scripts/wait-for-service.sh, stable/ocp-service-tls/templates/configmap.yaml
Updates logging in init container
=> ocp-service-tls: v0.2.2

stable/ocp-service-tls/Chart.yaml, stable/ocp-service-tls/templates/job.yaml
- Fixes annotate-service.sh script
=> ocp-service-tls: v0.2.3

stable/ibm-cp4d-watson-machine-learning-instance/.helmignore, stable/ibm-cp4d-watson-machine-learning-instance/Chart.yaml, stable/ibm-cp4d-watson-machine-learning-instance/templates/_helpers.tpl, stable/ibm-cp4d-watson-machine-learning-instance/templates/instance.yaml, stable/ibm-cp4d-watson-machine-learning-instance/values.yaml
Signed-off-by: Rogerio Silva <rogeriao@gmail.com>
=> WML Helm Chart

stable/ocp-oauth-github/.helmignore, stable/ocp-oauth-github/Chart.yaml, stable/ocp-oauth-github/README.md, stable/ocp-oauth-github/patches/oauth-patch.yaml, stable/ocp-oauth-github/scripts/_update-configmap.sh, stable/ocp-oauth-github/scripts/patch-oauth.sh, stable/ocp-oauth-github/scripts/remove-patch-oauth.sh, stable/ocp-oauth-github/support/configmap.snippet.yaml, stable/ocp-oauth-github/templates/NOTES.txt, stable/ocp-oauth-github/templates/_helpers.tpl, stable/ocp-oauth-github/templates/ca-config-map.yaml, stable/ocp-oauth-github/templates/configmap.yaml, stable/ocp-oauth-github/templates/delete-job.yaml, stable/ocp-oauth-github/templates/job.yaml, stable/ocp-oauth-github/templates/rbac.yaml, stable/ocp-oauth-github/templates/secret.yaml, stable/ocp-oauth-github/templates/serviceaccount.yaml, stable/ocp-oauth-github/values.yaml
- Provides implementation of chart to patch OAuth config with GitHub entry
=> ocp-oauth-github: v0.1.0

stable/ocp-oauth-htpasswd/.helmignore, stable/ocp-oauth-htpasswd/Chart.yaml, stable/ocp-oauth-htpasswd/README.md, stable/ocp-oauth-htpasswd/patches/oauth-patch.yaml, stable/ocp-oauth-htpasswd/scripts/_update-configmap.sh, stable/ocp-oauth-htpasswd/scripts/create-htpasswd-secret.sh, stable/ocp-oauth-htpasswd/scripts/patch-oauth.sh, stable/ocp-oauth-htpasswd/scripts/remove-patch-oauth.sh, stable/ocp-oauth-htpasswd/support/configmap.snippet.yaml, stable/ocp-oauth-htpasswd/templates/NOTES.txt, stable/ocp-oauth-htpasswd/templates/_helpers.tpl, stable/ocp-oauth-htpasswd/templates/configmap.yaml, stable/ocp-oauth-htpasswd/templates/delete-job.yaml, stable/ocp-oauth-htpasswd/templates/job.yaml, stable/ocp-oauth-htpasswd/templates/rbac.yaml, stable/ocp-oauth-htpasswd/templates/serviceaccount.yaml, stable/ocp-oauth-htpasswd/values.yaml
- Initial release of chart to deploy htpasswd oauth config
=> ocp-oauth-htpasswd: v0.1.0

stable/ocp-oauth-github/Chart.yaml, stable/ocp-oauth-github/templates/secret.yaml
- Fixes extra quotes in client secret - closes #418
=> ocp-oauth-github: v0.1.1

stable/ocp-console-notification/Chart.yaml, stable/ocp-console-notification/templates/console-notification.yaml
- Wraps color and text fields with quotes
=> ocp-console-notification: v0.2.1

stable/namespace/.helmignore, stable/namespace/Chart.yaml, stable/namespace/README.md, stable/namespace/templates/_helpers.tpl, stable/namespace/templates/gitops-configmap.yaml, stable/namespace/templates/namespace.yaml, stable/namespace/templates/operatorGroup.yaml, stable/namespace/templates/rbac.yaml, stable/namespace/values.yaml
- Creates namespace resource and rbac
- Optionally creates operator group and/or configmap
=> namespace: v0.1.0

stable/rbac/.helmignore, stable/rbac/Chart.yaml, stable/rbac/templates/_helpers.tpl, stable/rbac/templates/rbac.yaml, stable/rbac/templates/roleBindings.yaml, stable/rbac/values.yaml
- Initial version to generate rbac roles and role bindings
=> rbac: v0.1.0

stable/service-account/Chart.yaml, stable/service-account/templates/_helpers.tpl, stable/service-account/templates/rbac.yaml, stable/service-account/templates/roleBindings.yaml, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml, stable/service-account/templates/serviceaccount.yaml, stable/service-account/values.yaml
- Adds rbac rules and roles
- Cleans up input variables
=> service-account: v1.0.0

stable/service-account/Chart.yaml, stable/service-account/templates/scc-anyuid.yaml, stable/service-account/templates/scc-privileged.yaml
- Adds support for applying sccs to a namespace group of sccs
=> service-account: v1.1.0

stable/service-account/Chart.yaml, stable/service-account/templates/serviceaccount.yaml, stable/service-account/values.yaml
- Adds pullSecrets value to provide imagePullSecrets to the created service account
=> service-account: v1.2.0

stable/service-account/Chart.yaml, stable/service-account/templates/serviceaccount.yaml
- Fixes imagePullSecret structure
=> service-account: v1.2.1

stable/namespace/Chart.yaml, stable/namespace/templates/gitops-configmap.yaml, stable/namespace/templates/namespace.yaml, stable/namespace/templates/operatorGroup.yaml, stable/namespace/templates/rbac.yaml
- Updates sync waves to align with service-account sync waves
=> namespace: v0.2.0

stable/openshift-gitops/Chart.yaml, stable/openshift-gitops/templates/subscription.yaml, stable/openshift-gitops/values.yaml
- Exposes value to disable default ArgoCD instance - cloud-native-toolkit/terraform-tools-argocd#98
=> openshift-gitops: v0.10.0

stable/openshift-gitops-instance/Chart.yaml, stable/openshift-gitops-instance/templates/instance-config-map.yaml, stable/openshift-gitops-instance/templates/instance-job.yaml, stable/openshift-gitops-instance/templates/instance.yaml, stable/openshift-gitops-instance/values.yaml
- Adds logic to not install patching job if disableDefaultInstance flag is set to true - cloud-native-toolkit/terraform-tools-argocd#98
=> openshift-gitops-instance: v0.6.0

stable/openshift-gitops-instance/Chart.yaml, stable/openshift-gitops-instance/values.yaml
Updates default instance yaml to include `resourceCustomizations` with special logic for interpreting resource status - cloud-native-toolkit/terraform-tools-argocd#98
=> openshift-gitops-instance: v0.7.0

stable/ocp-machine-config-pids/.helmignore, stable/ocp-machine-config-pids/Chart.yaml, stable/ocp-machine-config-pids/templates/NOTES.txt, stable/ocp-machine-config-pids/templates/_helpers.tpl, stable/ocp-machine-config-pids/templates/container-runtime-config.yaml, stable/ocp-machine-config-pids/templates/kubelet-config.yaml, stable/ocp-machine-config-pids/values.yaml
- Add chart to create ContainerRuntimeConfig and KubeletConfig to set pidsLimit for a cluster
=> ocp-machine-config-pids: v0.1.0

stable/argocd-instance/Chart.yaml, stable/argocd-instance/templates/_helpers.tpl
- Adds missing argocd-instance.argocd-name helper function
=> argocd-instance: v0.1.1

stable/argocd-instance/Chart.yaml, stable/argocd-instance/values.yaml
=> argocd-instance: v0.1.3

stable/argocd-instance/Chart.yaml, stable/argocd-instance/templates/ingress.yaml, stable/argocd-instance/values.yaml
- Add configuration to generate the ingress using the tls_secret for the cluster
=> argocd-instance: v0.2.0

stable/argocd-instance/Chart.yaml, stable/argocd-instance/templates/empty-secret.yaml
- Add argocd-secret with empty string value for secretkey
=> argocd-instance: v0.3.0

stable/argocd-instance/Chart.yaml, stable/argocd-instance/templates/_helpers.tpl
- Adds app.kubernetes.io/part-of=argocd label to chart
=> argocd-instance: v0.3.1

stable/openshift-gitops/Chart.yaml, stable/openshift-gitops/templates/subscription.yaml, stable/openshift-gitops/values.yaml
=> openshift-gitops: v0.10.1

stable/argocd-instance/Chart.yaml, stable/argocd-instance/values.yaml
=> argocd-instance: v0.3.2

stable/tekton-operator/Chart.yaml, stable/tekton-operator/templates/post-install-hook.yaml, stable/tekton-operator/values.yaml
- Expose webhook name in variable
=> tekton-operator: v0.3.3

stable/resource-owner-job/.helmignore, stable/resource-owner-job/Chart.yaml, stable/resource-owner-job/README.md, stable/resource-owner-job/scripts/_update-configmap.sh, stable/resource-owner-job/scripts/create-owner-reference.sh, stable/resource-owner-job/support/configmap.snippet.yaml, stable/resource-owner-job/templates/_helpers.tpl, stable/resource-owner-job/templates/configmap.yaml, stable/resource-owner-job/templates/job.yaml, stable/resource-owner-job/templates/rbac.yaml, stable/resource-owner-job/templates/serviceaccount.yaml, stable/resource-owner-job/values.yaml
- Initial version to patch target with ownerReference
=> resource-owner-job: v0.1.0

stable/resource-owner-job/Chart.yaml, stable/resource-owner-job/templates/job.yaml
- Set job with helm hook and argocd wave
=> resource-owner-job: 0.2.0

stable/assign-group-cronjob/Chart.yaml, stable/assign-group-cronjob/templates/cronjob.yaml
- Update cronjob api version reference - #457
=> assign-group-cronjob: v0.2.2

stable/console-link-cronjob/Chart.yaml
- Touch chart to force a new release of repo index
=> console-link-cronjob: v0.5.3

stable/ibm-eventstreams-instance/Chart.yaml, stable/ibm-eventstreams-instance/templates/instance.yaml
Creating a new version of the Event Streams Instance Helm chart to allow annotations
=> new Event Streams Helm chart vertsion
