cloud-native-toolkit/toolkit-charts

- stable/developer-dashboard/values.yaml
- stable/swaggereditor/Chart.yaml
- stable/swaggereditor/templates/NOTES.txt
- stable/swaggereditor/templates/_helpers.tpl
- stable/swaggereditor/templates/deployment.yaml
- stable/swaggereditor/templates/ingress.yaml
- stable/swaggereditor/templates/role-binding.yaml
- stable/swaggereditor/templates/role.yaml
- stable/swaggereditor/templates/route.yaml
- stable/swaggereditor/templates/scc.yaml
- stable/swaggereditor/templates/service-account.yaml
- stable/swaggereditor/templates/service.yaml
- stable/swaggereditor/values.yaml
- Renames helper templates to match chart name
- Adds scc for openshift install
- Fixes clusterType test in ingress
- Updates apiVersion in route to allow deployment with kubectl apply
ibm-garage-cloud/planning#123
> SwaggerEditor v1.2.0 - Adds SCC

- stable/tool-config/Chart.yaml
- stable/tool-config/templates/application-menu.yaml
- stable/tool-config/values.yaml
- Adds global.clusterType to values that is used as optional check for application menu creation (moves test for clusterType == ocp4 into chart)
> tool-config: v0.7.0

- stable/developer-dashboard/Chart.yaml
- stable/developer-dashboard/templates/route.yaml
- stable/developer-dashboard/values.yaml
- Adds route for icons
- Bumps image version to v1.1.0
ibm-garage-cloud/planning#414
> developer-dashboard: v1.1.0

- stable/developer-dashboard/Chart.yaml
- stable/developer-dashboard/templates/route.yaml
- stable/developer-dashboard/values.yaml
- Changes `icons` route to use edge termination to fix issue
- Bumps image tag to 1.1.1
ibm-garage-cloud/planning#414
> developer-dashboard: v1.1.1

- stable/service-mesh-operator/Chart.yaml
- stable/service-mesh-operator/templates/instance.yaml
- stable/service-mesh-operator/values.yaml
- Extracts instance spec into values.yaml
- Adds instance logic for iks install
- Adds createInstance flag (defaulted to true) to have parity with other charts
> service-mesh-operator: v0.2.0

- stable/tool-config/Chart.yaml
- stable/tool-config/templates/_helpers.tpl
- stable/tool-config/templates/application-menu.yaml
- stable/tool-config/templates/config-map.yaml
- stable/tool-config/templates/secret.yaml
- Adds standard labels for all resources, particularly the helm.sh/chart and managed-by labels
> tool-config: v0.8.1

- stable/tool-test/.helmignore
- stable/tool-test/Chart.yaml
- stable/tool-test/templates/_helpers.tpl
- stable/tool-test/templates/ingress.yaml
- stable/tool-test/templates/route.yaml
- stable/tool-test/templates/service.yaml
- stable/tool-test/values.yaml
fixes ibm-garage-cloud/planning#352
Creates a helm chart that installs a 'dummy' ingress (on IKS), route (on OCP) and service (on both) to verify destroy does not delete them.
> add tool-test chart

- stable/ibmcloud/Chart.yaml
- stable/ibmcloud/templates/_helpers.tpl
- stable/ibmcloud/templates/config-map.yaml
- stable/ibmcloud/templates/secret.yaml
- Adds helper template for common labels
- Generates configmap and secret with new names (cloud-config and cloud-access) but leaves old ones for now for backward compatibility
> ibmcloud: v0.2.0

- stable/argocd-config/Chart.yaml
- stable/argocd-config/templates/applications.yaml
- stable/argocd-config/templates/namespaces.yaml
- stable/argocd-config/templates/project.yaml
- Fixes issue with using the label template in a loop
- Adds pre-install helm hook annotation to project to fix timing issue in Argo with applications created before project
> argocd-config: v0.13.1

- stable/cloud-setup/.helmignore
- stable/cloud-setup/Chart.yaml
- stable/cloud-setup/values.yaml
- Adds intial version of cloud-setup chart that creates ibmcloud, github, imageregistry, cloudnative toolkit doc config, and first-app doc config
ibm-garage-cloud/planning#501
> cloud-setup: v0.1.0

- stable/setup-job/Chart.yaml
- stable/setup-job/templates/job.yaml
- stable/setup-job/values.yaml
- Updates the job to use the CLI_VERSION environment variable
- Sets the cliVersion to 0.3.3 (the latest version of @ibmgaragecloud/cloud-native-toolkit-web-cli currently available
> setup-job: v0.2.0

- stable/starter-kit/Chart.yaml
- stable/starter-kit/templates/_helpers.tpl
- stable/starter-kit/templates/deployment.yaml
- stable/starter-kit/values.yaml
- Adds full set of labels to pod spec (not just selector labels)
- Adds `version` label to label set
- Adds `sidecar.istio.io/inject` annotation to the pods with corresponding flag
> starter-kit: v0.5.0

- stable/argocd-config/Chart.yaml
- stable/argocd-config/templates/_helpers.tpl
- stable/argocd-config/templates/project.yaml
- stable/argocd-config/values.yaml
- Adds repoUrl to project instead of using "*"
- Adds support for destinations (server and namespace) set in global values
- Adds argocd.argoproj.io/sync-wave annotation to project
> argocd-config: v0.17.0

- stable/openshift-gitops/.helmignore
- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/templates/_helpers.tpl
- stable/openshift-gitops/templates/group.yaml
- stable/openshift-gitops/templates/instance-config-map.yaml
- stable/openshift-gitops/templates/instance-job.yaml
- stable/openshift-gitops/templates/rbac.yaml
- stable/openshift-gitops/templates/subscription.yaml
- stable/openshift-gitops/values.yaml
- Provides initial version of helm chart that installs subscription and instance (via a job)
> openshift-gitops: v0.1.0

- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/templates/instance-config-map.yaml
- stable/openshift-gitops/templates/instance-job.yaml
- stable/openshift-gitops/templates/rbac.yaml
- Generates job in openshift-operators namespace because openshift-gitops does not exist initially
- Configure serviceaccount for job with permission to work on resources in openshift-gitops namespace
> openshift-gitops: v0.4.0

- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/values.yaml
- Updates default channel to 'stable' for subscription
> openshift-gitops: v0.6.0

- stable/console-link-cronjob/.helmignore
- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/templates/_helpers.tpl
- stable/console-link-cronjob/templates/configmap.yaml
- stable/console-link-cronjob/templates/cronjob.yaml
- stable/console-link-cronjob/templates/rbac.yaml
- stable/console-link-cronjob/templates/serviceaccount.yaml
- stable/console-link-cronjob/values.yaml
- Adds chart to create a cronjob (and optionally the required serviceaccount and rbac
> console-link-cronjob: v0.1.0

- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/templates/configmap.yaml
- Writes temporary file into /tmp directory to prevent error writing to read-only directory
> console-link-cronjob: v0.1.1

- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/templates/rbac.yaml
Fixes https://github.com/cloud-native-toolkit/planning/issues/849
openshift-gitops now have new service accounts names
> Add argocd serviceaccounts

- stable/console-link-cronjob/.helmignore
- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/README.md
- stable/console-link-cronjob/scripts/_update-configmap.sh
- stable/console-link-cronjob/scripts/reconcile-ibm-observe-console-links.sh
- stable/console-link-cronjob/scripts/reconcile-route-console-links.sh
- stable/console-link-cronjob/support/configmap.snippet.yaml
- stable/console-link-cronjob/templates/configmap.yaml
- Adds support for generating console links from config maps (particularly for components hosted outside the cluster)
- Adds README to document usage
- Moves script logic into scripts/ folder and adds _update-configmap.sh to update the contents of templates/configmap.yaml
> console-link-cronjob: v0.4.0

- stable/argocd-config/Chart.yaml
- stable/argocd-config/templates/applications.yaml
- stable/argocd-config/values.yaml
- Adds pathSuffix to support defining application paths that include additional path values
> argocd-config: v0.19.0

- stable/developer-dashboard/Chart.yaml
- stable/developer-dashboard/values.yaml
- Updates default repository url to quay.io/ibmgaragecloud/developer-dashboard
- Updates default tag to v1.4.4
> developer-dashboard: v1.4.0

- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/templates/cronjob.yaml
- Wraps monitor and logging images strings in quotes for environment variables to prevent issues
> console-link-cronjob: v0.4.1

- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/scripts/reconcile-ibm-observe-console-links.sh
- stable/console-link-cronjob/templates/configmap.yaml
- Adds logic to reconsole-ibm-observe-console-links.sh to determine the guid (and therefore the correct url to the service) from the configmap
> console-link-cronjob: v0.5.0

- stable/starter-kit/Chart.yaml
- stable/starter-kit/templates/deployment.yaml
- Adds JAEGER_SERVICE_NAME and IMAGE_NAME environment variables to the deployment
> starter-kit: v0.6.1

- stable/starter-kit/Chart.yaml
- stable/starter-kit/templates/_helpers.tpl
- stable/starter-kit/templates/deployment.yaml
- Determines appropriate initialDelaySeconds value for liveness and reqdiness probes based on runtime value
> starter-kit: v0.6.2

- stable/ocs-operator/Chart.yaml
- stable/ocs-operator/templates/storage-storagecluster.yaml
- stable/refarch-infraconfig/Chart.yaml
- stable/refarch-infraconfig/templates/infrastructure-imageregistry.yaml
- stable/refarch-infraconfig/templates/infrastructure-ingresscontroller.yaml
Helm charts generates error from envFrom under pod.
> Modified charts for infraconfig and ocs-operator 

- stable/assign-group-cronjob/Chart.yaml
- stable/assign-group-cronjob/scripts/reconcile-users-in-group.sh
- stable/assign-group-cronjob/templates/configmap.yaml
- stable/assign-group-cronjob/templates/cronjob.yaml
- stable/assign-group-cronjob/values.yaml
- Adds support for providing a list of groups to assign users
> assign-group-cronjob: v0.2.0

- stable/console-link-configmap/Chart.yaml
- stable/console-link-configmap/templates/_helpers.tpl
- stable/console-link-configmap/templates/configmap.yaml
- stable/console-link-configmap/values.schema.json
- stable/console-link-configmap/values.yaml
- Adds otherValues entry to values to allow more data than url to be added to the configmap
> console-link-configmap: v0.2.0

- stable/tool-config/Chart.yaml
- stable/tool-config/templates/_helpers.tpl
- stable/tool-config/templates/config-map.yaml
- Fixes logic for console-link.cloud-native-toolkit.dev/enabled label
> tool-config: v0.12.1

- stable/ibm-catalogs/Chart.yaml
- stable/ibm-catalogs/templates/ibm-automation-foundation-core-operator-catalog.yaml
- stable/ibm-catalogs/templates/ibm-common-services-operator-catalog.yaml
- stable/ibm-catalogs/templates/ibm-operator-catalog.yaml
- stable/ibm-catalogs/templates/ibm-process-mining-operator-catalog.yaml
- stable/ibm-catalogs/values.yaml
- Adds sync-wave annotation and input value to install the catalog before the operators
> ibm-catalogs: v0.3.0

- stable/argocd-config/Chart.yaml
- stable/argocd-config/templates/_helpers.tpl
- Removes prefix from project name (prefix only applies to apps)
> argocd-config: v0.21.1

- stable/argocd-operator/Chart.yaml
- stable/argocd-operator/templates/rbac.yaml
- Updates controller RBAC to use the service account group for the subject
> argocd-operator: v0.5.0

- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/templates/rbac.yaml
- Updates controller RBAC to use the service account group for the subject
> openshift-gitops: v0.8.0

- stable/service-account/Chart.yaml
- stable/service-account/templates/scc-anyuid.yaml
- stable/service-account/templates/scc-privileged.yaml
- stable/service-account/templates/serviceaccount.yaml
Post-install hooks were causing problems deploying the Instana Robot Shop chart.  We need the SA and SCC's installed first.
> Change service account to use helm pre-install hooks

- stable/ibm-platform-navigator/Chart.yaml
- stable/ibm-platform-navigator/templates/subscription.yaml
- stable/ibm-platform-navigator/values.yaml
- Sets sync-wave annotation to -5
> ibm-platform-navigator: v0.3.0

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/values.yaml
- Adds default configuration for RBAC
- Enables openShiftOAuth by default
> openshift-gitops-instance: v0.2.0

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/templates/_helpers.tpl
- stable/openshift-gitops-instance/templates/group.yaml
- stable/openshift-gitops-instance/templates/instance-config-map.yaml
- stable/openshift-gitops-instance/templates/instance-job.yaml
- stable/openshift-gitops-instance/templates/instance.yaml
- stable/openshift-gitops-instance/templates/rbac.yaml
- stable/openshift-gitops-instance/values.yaml
- stable/openshift-gitops/Chart.yaml
- stable/openshift-gitops/values.yaml
- Moves OpenShift GitOps instance logic out of openshift-gitops chart and merged into openshift-gitops-instance
> Updates openshift-gitops and openshift-gitops-instance

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/templates/post-delete-hook.yaml
- Adds ibmcloud.ibm.com/services to the RBAC rules for the delete service account
> ibm-portworx: v0.2.4

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/templates/post-delete-hook-config.yaml
- stable/ibm-portworx/templates/post-delete-hook.yaml
- Moves delete logic into a Sync hook to clean up portworx immediately after it is deleted during a delete operation
> ibm-portworx: v0.2.6

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/support/configmap-delete.snippet.yaml
- stable/ibm-portworx/templates/post-delete-hook-config.yaml
- stable/ibm-portworx/templates/post-delete-hook.yaml
- Removes argocd hooks for delete logic (will be replaced with finalizer)
> ibm-portworx: v0.2.7

- stable/ibmcloud-operator/Chart.yaml
- stable/ibmcloud-operator/templates/subscription.yaml
- Removes pre-install helm hook annotation
> ibmcloud-operator: v0.2.2

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/templates/portworx-service.yaml
- stable/ibm-portworx/templates/storageclasses.yaml
- Adds storage classes to the chart
- Changes the sync-wave to -1 for the portworx service and the storage classes
cloud-native-toolkit/terraform-gitops-ibm-portworx#4
> ibm-portworx: v0.3.0

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/templates/_helpers.tpl
- stable/ibm-portworx/templates/configmap.yaml
- stable/ibm-portworx/templates/daemonset.yaml
- stable/ibm-portworx/templates/job.yaml
- stable/ibm-portworx/templates/operator-configmap.yaml
- stable/ibm-portworx/templates/operator-secret.yaml
- stable/ibm-portworx/templates/portworx-service.yaml
- stable/ibm-portworx/templates/post-delete-hook-config.yaml
- stable/ibm-portworx/templates/post-delete-hook.yaml
- stable/ibm-portworx/templates/rbac.yaml
- stable/ibm-portworx/templates/serviceaccount.yaml
Updates the chart to deploy only to kube-system namespace
> ibm-portworx: v0.4.0

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/templates/_helpers.tpl
- stable/openshift-gitops-instance/templates/instance-config-map.yaml
- stable/openshift-gitops-instance/templates/instance-job.yaml
- stable/openshift-gitops-instance/values.yaml
- Updates logic to build the openshift-gitops instance name to prevent two instances in the same namespace
- Adds ttlSecondsAfterFinish to 300 (5 minutes) to remove the job after deployment
cloud-native-toolkit/software-everywhere#169
> openshift-gitops-instance: v0.5.1

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/templates/_helpers.tpl
- stable/openshift-gitops-instance/templates/instance-config-map.yaml
- stable/openshift-gitops-instance/templates/instance.yaml
- stable/openshift-gitops-instance/values.yaml
Adds optional created-by label via createdBy value - cloud-native-toolkit/terraform-tools-argocd#72
> openshift-gitops-instance: v0.5.2

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/templates/instance.yaml
- stable/openshift-gitops-instance/templates/rbac.yaml
Fixes name in argocd instance and empty spaces in rbac roles
> openshift-gitops-instance: v0.5.3

- stable/tekton-operator/Chart.yaml
- stable/tekton-operator/templates/post-install-hook.yaml
- stable/tekton-operator/values.yaml
- Adds service account and job as post-install hooks to verify the tekton webhook has started
> tekton-operator: v0.3.0

- stable/openshift-gitops-instance/Chart.yaml
- stable/openshift-gitops-instance/templates/rbac.yaml
- Addresses timing issue for ArgoCD deletions by marking RBAC resources as pre-install hooks
cloud-native-toolkit/terraform-tools-argocd#89
> openshift-gitops-instance: v0.5.4

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/scripts/volume-create.sh
- stable/ibm-portworx/templates/configmap.yaml
- Adds clusterid, workerid, and storage tags to the created volumes
> ibm-portworx: v0.5.0

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/values.yaml
- Updates default values for volume variables (iops:3000, capacity:200, profile:10iops-tier)
> ibm-portworx: v0.6.1

- stable/ibm-portworx/Chart.yaml
- stable/ibm-portworx/scripts/volume-attach.sh
- stable/ibm-portworx/scripts/volume-attachment-destroy.sh
- stable/ibm-portworx/scripts/volume-create.sh
- stable/ibm-portworx/scripts/volume-manage.sh
- stable/ibm-portworx/templates/configmap.yaml
- stable/ibm-portworx/templates/daemonset.yaml
- stable/ibm-portworx/values.yaml
- Allows for suffix volume name to differentiate volumes from different deployments
> ibm-portworx: v0.8.0

- stable/ocp-service-tls/.helmignore
- stable/ocp-service-tls/Chart.yaml
- stable/ocp-service-tls/scripts/_update-configmap.sh
- stable/ocp-service-tls/scripts/annotate-service.sh
- stable/ocp-service-tls/scripts/wait-for-service.sh
- stable/ocp-service-tls/support/configmap.snippet.yaml
- stable/ocp-service-tls/templates/_helpers.tpl
- stable/ocp-service-tls/templates/configmap.yaml
- stable/ocp-service-tls/templates/job.yaml
- stable/ocp-service-tls/templates/rbac.yaml
- stable/ocp-service-tls/templates/serviceaccount.yaml
- stable/ocp-service-tls/values.yaml
Adds chart to create a job that will add service.beta.openshift.io/serving-cert-secret-name annotation to existing Service and optionally create config map with service.beta.openshift.io/inject-cabundle=true annotation
> ocp-service-tls: v0.1.0

- stable/ocp-service-tls/Chart.yaml
- stable/ocp-service-tls/scripts/wait-for-service.sh
- stable/ocp-service-tls/templates/configmap.yaml
Fixes typo in wait-for-service.sh script
> ocp-service-tls: v0.2.1

- stable/tool-config/Chart.yaml
- stable/tool-config/templates/_helpers.tpl
- stable/tool-config/templates/config-map.yaml
Surpresses config map creation if the public url and the otherConfig is empty
> tool-config: v0.14.0

- stable/rbac/Chart.yaml
- stable/rbac/templates/rbac.yaml
- stable/rbac/templates/roleBindings.yaml
Removes serviceAccount name and namespace as required fields. If the serviceAccount name is not provided then the rule defaults to granting access to group of all service accounts in the provided namespace. If the serviceAccount namespace is not provided the namespace defaults to the one provided for the chart.
> rbac: v0.2.0

- stable/service-account/Chart.yaml
- stable/service-account/templates/rbac.yaml
- Fixes "incompatible types for comparison" issue with clusterScope when rbac rules provided
> service-account: v1.0.1

- stable/watson-nlp/Chart.yaml
- stable/watson-nlp/templates/deployment.yaml
Moving the logic for adding security context into the range block for initContainers
> Fixes for security warnings with >1 model

- stable/argocd-instance/Chart.yaml
- stable/argocd-instance/templates/_helpers.tpl
- stable/argocd-instance/values.yaml
- Updates instance name to just "gitops" if installing into "gitops" namespace (instead of "gitops-gitops")
- Adds empty host value for instance
> argocd-instance: v0.1.2

- stable/ibm-catalogs/templates/ibm-operator-catalog.yaml
Hi @seansund and/or @hollisc, could you please look at this PR which is meant to add support for the general IBM Catalog to support OLM to deploy specific IBM Catalog version based on the exact Kubernetes Version your cluster is running as opposed to always deploy latest? This is based on what I could read at https://www.ibm.com/docs/en/cloud-paks/1.0?topic=clusters-adding-operator-catalog
Thanks
> adding specific kubernetes version ibm catalog version

- stable/console-link-cronjob/Chart.yaml
- stable/console-link-cronjob/templates/cronjob.yaml
- Add logic to use the appropriate version of CronJob api available on the server
> console-link-cronjob: v0.5.2

- stable/namespace-rbac-cronjob/Chart.yaml
- stable/namespace-rbac-cronjob/templates/cronjob.yaml
- Update cronjob api version to fix deprecation error - #457
> namespace-rbac-cronjob: v0.2.1
